version: '3.9'
services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/campusthreads
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
    ports:
      - "4000:4000"
    depends_on:
      - mongo
      - redis
    volumes:
      - ./services/api:/usr/src/app
      - /usr/src/app/node_modules
volumes:
  mongo_data:
